### ISSUE TITLE
Azure did not build js files

### ISSUE THREAD

**Issue by getsetbro** [adrianhall/grumpy-wizards#3]
Thanks for this repo. I tried adding a react-router app to azure but I didn't know how to have a .ps1 file.

I downloaded and deployed this repo to an azure site of mine. The following files were not created so I created so I allowed them in the ignore file.
<script src="vendor.bundle.js"></script>
<script src="grumpywizards.js"></script>

Is something broken?

**Comment by adrianhall** [comment]
You did not include a list of files.

However, I deploy this site to azure myself via continuous deployment directly from GitHub.  From your App Service, click on All Settings; Continuous Deployment - it will prompt you for the deployment source, credentials, project and branch.  Once that is done, you should get it deployed no problem.

**Comment by getsetbro** [comment]
I am also using continuous deployment, however mine is local.

**Comment by adrianhall** [comment]
I have a deploy.cmd / .deployment files that do an npm run build after the npm install.  You can generate these using the azure cli easily enough.  I should probably check those in.  Here is the reference: https://shellmonger.com/2015/08/29/continuous-deployment-nodejs-and-microsoft-azure/

**Comment by getsetbro** [comment]
Thanks. Universal JS in azure articles are hard to find.
