### ISSUE TITLE
Test command not working.

### ISSUE THREAD

**Issue by Itagiba** [adrianhall/grumpy-wizards#4]
I have followed your example by adding mocha and:

```"test": "mocha --require ignore-styles --recursive --compilers js:babel-register --reporter dot client/test server/test",```

To may package.json file but nothing happens and babel still thinks my sass files are javascript:

```Leading decorators must be attached to a class declaration```

How do I make babel-register ignore style files?

**Comment by adrianhall** [comment]
You will have to take this up with the mocha / ignore-styles guys.  I can't really answer for them.  All I can say is that it works for me.  ignore-styles is here: https://www.npmjs.com/package/ignore-styles
