### ISSUE TITLE
No scss files in repo

### ISSUE THREAD

**Issue by jamiehutber** [adrianhall/grumpy-wizards#5]
Hey

Thanks for putting this together. I'm struggling to get webfonts included in my webpack build. 

I found your blog https://shellmonger.com/2016/01/22/working-with-fonts-with-webpack/ which led me to the repo.

Do you know which repo I might find the setup you described in the blog? I'd like to play with why your version is working and mine is not.

Cheers

**Comment by adrianhall** [comment]
Go back to tag 2016-02-02 - or something around the time of the blog.  I tag things when I write the blog. 

I'm coming back round to SCSS.  Personal opinion is that I don't think the react community knows how to deal with style sheets yet, so there is a lot of competing solutions.  This is just one.

**Comment by jamiehutber** [comment]
Thanks :) In the end it was actually my paths in the index.html. 

Without the repo I wouldn't have worked it out.
